import Footer from "@/shared/ui/Footer";
import Header from "@/shared/ui/Header";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";



export default function Home() {
const [modalActive, setModalActive] = useState(true)

  return (
    <>
      <Head>
        <title>proper nutrition</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main>
          <section className="white_bac">
              <Header/>
            <div className="container">
              <div className="banner_1">
                 <div className="banner_1_left">
                  <p className="txt_1">
                    Free Meals delivered <br />
                    <sp className="sp">to your doorstep!</sp>
                  </p>

                  <p className="txt_2">
                    We provide healthy, balanced meals <br />
                    delivered to your doorstep!
                  </p>

                  <div className="button_block">
                     <button className="btn_1">
                      <Link href="#" className="lnk_2">
                      How It Works
                      </Link>
                     </button>

                     <buttton className="btn_2">
                      Get Started
                     </buttton>
                  </div>

                 </div>

                 <div className="bnr">
                  <img src="./img/bnr.png" alt="" />
                 </div>
              </div>
            </div>
          </section>

           <section className="white_bac">
            <div className="container">
              <div className="about_block">
                <div className="about_top">
                     <div className="about_top_elm">
                      <div className="itm_1">
                        <img src="./img/flag.svg" alt="" />
                      </div>

                      <div className="about_txt">
                         <p className="txt_3">AAA & State Governments</p>
                         <p className="txt_4">
                          Information for leaders in <br />
                          government or at Area Agencies <br />
                          on Aging.
                         </p>
                      </div>
                     </div>

                     <div className="about_top_elm">
                      <div className="itm_1">
                        <img src="./img/itm.svg" alt="" />
                      </div>

                      <div className="about_txt">
                         <p className="txt_3">Case Managers</p>
                         <p className="txt_4">
                          Information for case managers <br />
                          who are looking for solutions for<br />
                          their clients or members.
                         </p>
                      </div>
                     </div>

                     <div className="about_top_elm">
                      <div className="itm_1">
                        <img src="./img/itm_2.svg" alt="" />
                      </div>

                      <div className="about_txt">
                         <p className="txt_3">Individuals & Caregivers</p>
                         <p className="txt_4">
                          For self-pay customers  <br />
                          managing a chronic disease, <br />
                          living independently, or caring.
                         </p>
                      </div>
                     </div>
                </div>

                <div className="about_banner">
                  <div className="about_banner_left">
                  {/* <div className="bnr_lm">
                    <img src="./img/itm_3.svg" alt="" />
                  </div> */}
                   <p className="txt_5">About Us</p>

                   <p className="txt_6">
                    Meals America provides home-delivered meals to  <br />
                    consumers across all 67 counties in Florida. We offer a  <br />
                    wide variety of frozen, refrigerated, and shelf-stable  <br />
                    meals including dinners, deli café, breakfasts, soups, and   <br />
                    specialty weeks.
                    <br />
                    <br />

                     We also provide option for customers with dietary <br />
                     restrictions and have vegetarian, sodium-controlled, and  <br />
                     gluten-free menus. We also provide emergency packs for   <br />
                     emergency situations that contain shelf stable items only  <br />
                     and do not require refrigeration or heating. 
                   </p>


                   <button className="btn_3">
                     <Link href="#" className="lnk_3">
                     Read more
                     </Link>
                   </button>


                   <div className="bnr_ul">
                     <ul className="list">
                      <li className="li">
                           <label class="custom-checkbox">
                            <input type="checkbox"/>
                            <span class="checkmark"></span>
                             Gluten free options
                            </label>
                      </li>

                       <li className="li">
                           <label class="custom-checkbox">
                            <input type="checkbox"/>
                            <span class="checkmark"></span>
                             Exact calorie content
                            </label>
                      </li>

                       <li className="li">
                           <label class="custom-checkbox">
                            <input type="checkbox"/>
                            <span class="checkmark"></span>
                             Improves health
                            </label>
                      </li>
                     </ul>

                     <ul className="list">
                      <li className="li">
                           <label class="custom-checkbox">
                            <input type="checkbox"/>
                            <span class="checkmark"></span>
                             Vegetarian options
                            </label>
                      </li>

                       <li className="li">
                           <label class="custom-checkbox">
                            <input type="checkbox"/>
                            <span class="checkmark"></span>
                             Adds strength and energy
                            </label>
                      </li>
                     </ul>
                   </div>
                  </div>
                 
                 <div className="about_banner_rigth">
                  <img src="./img/lm.svg" alt="" />
                 </div>
                </div>
              </div>

            </div>
           </section>

           <section className="white_bac">
            <div className="container">
              <div className="why_choose_us_block">
                  <div className="wh_pht">
                    <img src="./img/wh_pht.svg" alt="" />
                  </div>

                 <div className="why_left">
                  <div className="why_left_top">
                    <p className="txt_7">Our benefits</p>
                    <div className="line"></div>
                  </div>

                  <p className="txt_8">Why choose us?</p>
                  <p className="txt_9">
                    We are proud to provide a healthy and nutritious meal for <br />
                    those in need! We listen to your preferences and customize  <br />
                    the weekly menu considering your requests! Your health is our  <br />
                    priority!
                  </p>


                  <div className="why_block">
                    <div className="why_block_itm">
                      <div className="why_icon">
                        <img src="./img/Hamburger.svg" alt="" />
                      </div>


                      <p className="txt_10">Delicious & Healthy</p>
                    </div>
                       
                     <div className="why_block_itm">
                      <div className="why_icon">
                        <img src="./img/suckers.svg" alt="" />
                      </div>


                      <p className="txt_10">Ready to heat</p>
                    </div>


                    <div className="why_block_itm">
                      <div className="why_icon">
                        <img src="./img/Truck.svg" alt="" />
                      </div>


                      <p className="txt_10">Delivery</p>
                    </div>

                    <div className="why_block_itm">
                      <div className="why_icon">
                        <img src="./img/p.svg" alt="" />
                      </div>


                      <p className="txt_10">Taste and preferences</p>
                    </div>  
                  </div>
                 </div>
              </div>
            </div>
           </section>

           <section className="white_bac">
            <div className="container">
              <div className="chs_block">

                <p className="txt_11">Nutrition plans</p>
                <p className="txt_12">Choose Your Nutrition</p>

                <div className="wh_elm">
                   <div className="cabb">
                  <img src="./img/cabbeg.svg" alt="" />
                </div>
                
                  <div className="wh_elm_top">
                     <div className="wh_itm">
                      <img src="./img/gourmet.svg" alt="" />
                     </div>

                      <div className="wh_itm">
                      <img src="./img/gourmet.svg" alt="" />
                     </div>

                      <div className="wh_itm">
                      <img src="./img/comfort.svg" alt="" />
                     </div>

                      <div className="wh_itm">
                      <img src="./img/deli.svg" alt="" />
                     </div>

                      <div className="wh_itm">
                      <img src="./img/fam.svg" alt="" />
                     </div>

                      <div className="wh_itm">
                      <img src="./img/in.svg" alt="" />
                     </div>
                  </div>

                  <div className="wh_bottom">
                     <div className="wh_bottom_left">
                      <img src="./img/wh_left.svg" alt="" />
                     </div>

                     <div className="wh_bottom_rigth">
                      <p className="txt_13">Meals includes:</p>

                      <ul className="ul_1">
                        <li>Loaf of Bread</li>
                        <li>Sticks of Butter</li>
                        <li>Quart of Juice</li>
                        <li>Half Callon of 2% Milk</li>
                        <li>Box of Cereal or Oat Meal</li>
                        <li>Package of Cheese Sticks or Cheese Slices</li>
                        <li>Pack of Fruits Cups</li>
                        <li>Complimentary Dessert</li>
                      </ul>

                      <div className="wh_bottom_btn_block">
                        <button className="btn_4">
                          Download Menu
                        </button>

                        <button className="btn_5">
                          Get Started
                        </button>
                      </div>
                     </div>

                  </div>
                </div>

              </div>
            </div>
           </section>

           <section className="bnrr">
            <div className="container">
              <div className="sch_block">
                  
                  <div className="bnr_itm">
                   <p className="txt_14">
                    Schedule your first <br />
                    <span className="sp_1">weekly</span>
                    delivery
                   </p>

                   <button className="btn_6">
                         Get Started
                   </button>
                  </div>
              </div>
            </div>
           </section>

           <section className="white_bac">
            <div className="container">
              <div className="who_we_block">
                <div className="wh_left">
                   <div className="wh_top">
                     <p className="txt_15">Who We Serve?</p>
                    <div className="line"></div>
                   </div>

                   <p className="txt_16">Who We Serve?</p>
                   <p className="txt_17">
                    We serve those in need for long-term meal assistance or <br />
                    anyone who might be in need of a short-term plan while <br />
                    recovering from an injury or illness, or who would simply enjoy   <br />
                    healthy meals that require minimal preparation time.
                   </p>

                   <div className="wh_bl">
                    <div className="wh_bl_lft">
                       <div className="wh_icon">
                        <img src="./img/tim.svg" alt="" />
                       </div>

                       <p className="txt_18">
                        Monday - Friday <br />
                        9:00 AM - 5:00 PM
                       </p>
                    </div>

                    <div className="wh_bl_lft">
                       <div className="wh_icon">
                        <img src="./img/phone.svg" alt="" />
                       </div>

                       <p className="txt_18">
                        (786) 600-59-09
                       </p>
                    </div>
                   </div>

                    <button className="btn_7">
                           Read more
                    </button>

                </div>

                <div className="wh_rigth">
                  <img src="./img/br.svg" alt="" />
                </div>
              </div>

            </div>
           </section>

           <section>
              <Footer/>
           </section>
        </main>
      </div>
    </>
  );

}
